-- =========================================================================
-- SCRIPT DE ACTUALIZACIÓN DE BASE DE DATOS (MUSEO DE IVONNE)
-- Copia y pega este script completo en el SQL Editor de tu consola de Supabase
-- =========================================================================

-- 1. Agregar nuevas columnas a la tabla semana_museo_v2 si no existen
ALTER TABLE semana_museo_v2 ADD COLUMN IF NOT EXISTS cancion_caratula TEXT;
ALTER TABLE semana_museo_v2 ADD COLUMN IF NOT EXISTS curiosidad_cuadro TEXT;
ALTER TABLE semana_museo_v2 ADD COLUMN IF NOT EXISTS poema TEXT;
ALTER TABLE semana_museo_v2 ADD COLUMN IF NOT EXISTS autor_poema TEXT;
ALTER TABLE semana_museo_v2 ADD COLUMN IF NOT EXISTS tecnica_pintura TEXT;
ALTER TABLE semana_museo_v2 ADD COLUMN IF NOT EXISTS cancion_titulo TEXT;
ALTER TABLE semana_museo_v2 ADD COLUMN IF NOT EXISTS cancion_autor TEXT;

-- 2. Asegurar la existencia de la tabla respuestas_amiga
CREATE TABLE IF NOT EXISTS respuestas_amiga (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    dia_id INT NOT NULL,
    respuesta TEXT NOT NULL
);

-- 3. Desactivar RLS (Row Level Security) para permitir que la web suba e inserte datos directamente
ALTER TABLE semana_museo_v2 DISABLE ROW LEVEL SECURITY;
ALTER TABLE respuestas_amiga DISABLE ROW LEVEL SECURITY;

-- 4. Mensaje de confirmación
SELECT 'Base de datos del museo actualizada con éxito' as status;
